# Generated by Django 6.0.1 on 2026-01-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('paid', 'Oplacone'), ('shipped', 'Wyslane'), ('canceled', 'Anulowane')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='tea',
            name='caffeine_level',
            field=models.CharField(choices=[('none', 'Bez kofeiny'), ('low', 'Niska'), ('medium', 'Srednia'), ('high', 'Wysoka')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tea',
            name='tea_type',
            field=models.CharField(choices=[('black', 'Czarna'), ('green', 'Zielona'), ('white', 'Biala'), ('oolong', 'Oolong'), ('herbal', 'Ziolowa'), ('puerh', 'Puerh')], max_length=10),
        ),
    ]
