# Generated by Django 6.0.1 on 2026-01-27 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teastore', '0002_alter_order_status_alter_tea_caffeine_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data dostawy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('paid', 'Oplacone'), ('shipped', 'Wyslane'), ('canceled', 'Anulowane')], default='new', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teastore.order', verbose_name='Zamowienie'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Ilosc'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teastore.tea', verbose_name='Herbata'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena jednostkowa'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Kod kraju'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='farm_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Plantacja'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='is_organic',
            field=models.BooleanField(default=False, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='region',
            field=models.CharField(max_length=60, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='added_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='caffeine_level',
            field=models.CharField(choices=[('none', 'Bez kofeiny'), ('low', 'Niska'), ('medium', 'Srednia'), ('high', 'Wysoka')], max_length=10, verbose_name='Poziom kofeiny'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teastore.teacategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywna'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teastore.origin', verbose_name='Pochodzenie'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Stan magazynowy'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='tea_type',
            field=models.CharField(choices=[('black', 'Czarna'), ('green', 'Zielona'), ('white', 'Biala'), ('oolong', 'Oolong'), ('herbal', 'Ziolowa'), ('puerh', 'Puerh')], max_length=10, verbose_name='Typ herbaty'),
        ),
        migrations.AlterField(
            model_name='teacategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='teacategory',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nazwa'),
        ),
    ]
