from django.urls import path

from .views import (
    register_user,
    user_login,
    user_logout,
    teas_search,
    orders_my,
    tea_list,
    tea_detail,
    tea_update_delete,
    category_list,
    category_detail,
    origin_list,
    origin_detail,
    order_list,
    order_detail,
    order_item_list,
    order_item_detail,
    tea_list_html,
    tea_detail_html,
    tea_create_html,
    category_list_html,
    category_detail_html,
    category_create_html,
    origin_list_html,
    origin_detail_html,
    origin_create_html,
    order_list_html,
    order_detail_html,
    order_create_html,
    order_item_list_html,
    order_item_detail_html,
    order_item_create_html,
)

urlpatterns = [
    path("auth/register/", register_user, name="register-user"),
    path("login/", user_login, name="user-login"),
    path("logout/", user_logout, name="user-logout"),
    path("teas/", tea_list),
    path("teas/<int:pk>/", tea_detail),
    path("teas/update_delete/<int:pk>/", tea_update_delete),
    path("categories/", category_list),
    path("categories/<int:pk>/", category_detail),
    path("origins/", origin_list),
    path("origins/<int:pk>/", origin_detail),
    path("orders/", order_list),
    path("orders/<int:pk>/", order_detail),
    path("order-items/", order_item_list),
    path("order-items/<int:pk>/", order_item_detail),
    path("teas/search/", teas_search, name="teas-search"),
    path("orders/my/", orders_my, name="orders-my"),
    path("html/teas/", tea_list_html, name="tea-list-html"),
    path("html/teas/<int:id>/", tea_detail_html, name="tea-detail-html"),
    path("html/teas/dodaj/", tea_create_html, name="tea-create-html"),
    path("html/categories/", category_list_html, name="category-list-html"),
    path("html/categories/<int:id>/", category_detail_html, name="category-detail-html"),
    path("html/categories/dodaj/", category_create_html, name="category-create-html"),
    path("html/origins/", origin_list_html, name="origin-list-html"),
    path("html/origins/<int:id>/", origin_detail_html, name="origin-detail-html"),
    path("html/origins/dodaj/", origin_create_html, name="origin-create-html"),
    path("html/orders/", order_list_html, name="order-list-html"),
    path("html/orders/<int:id>/", order_detail_html, name="order-detail-html"),
    path("html/orders/dodaj/", order_create_html, name="order-create-html"),
    path("html/order-items/", order_item_list_html, name="order-item-list-html"),
    path("html/order-items/<int:id>/", order_item_detail_html, name="order-item-detail-html"),
    path("html/order-items/dodaj/", order_item_create_html, name="order-item-create-html"),
]
